/** Sources de données (aligné sur l'enum Drizzle source_kind). */
export type SourceKind =
  | "sirene"
  | "bodacc"
  | "inpi"
  | "tresor_gels"
  | "opensanctions"
  | "gleif"
  | "vies"
  | "ban"
  | "gdelt"
  | "pappers"
  | "companies_house"
  | "recherche_entreprises"
  | "balo"
  | "boamp"
  | "joafe"
  | "dca"
  | "manual"
  | "fixture";
